"""
Django settings for example project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5hp%lx#%$7g%sse1xrk=p%s$@@=#5=)*0g@_5qdd2fwp10c-ru'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'example.polls.apps.PollsConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
]

MIDDLEWARE = []

ROOT_URLCONF = 'example.urls'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': f"{BASE_DIR}/example/example.sqlite3",
    }
}

DRF_REACT_TEMPLATE_TYPE_MAP = {
    'ImageField': {'type': 'file'},
}
